version: '3.9'
name: dock-php-nginx-1
services:
  nginx_default:
    container_name: nginx_default
    image: nginx:1.23.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data:/var/www
    links:
      - php_default
  php_default:
    container_name: php_default
    image: php:8.2-fpm
    working_dir: /var/www
    volumes:
      - ./data:/var/www
    command: docker-php-ext-install mysqli pdo pdo_mysql
